name: dataforge_cli
description: A Dart code generator that forges data classes with JSON serialization support from annotated classes.
version: 0.6.1
homepage: https://github.com/your_username/dataforge
repository: https://github.com/your_username/dataforge
issue_tracker: https://github.com/your_username/dataforge/issues
documentation: https://github.com/your_username/dataforge#readme

executables:
  dataforge: dataforge_cli

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  analyzer: ^8.1.1
  collection: ^1.17.0
  path: ^1.7.0
  args: ^2.7.0
  dataforge_annotation: 
  dataforge_base: 

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15


dependency_overrides: 
  dataforge_annotation: 
    path: ../annotation
  dataforge_base:
    path: ../dataforge_base
