name: dataforge_base
description: Base package for dataforge containing models, parser, and writer.
version: 0.6.0-dev.4
homepage: https://github.com/lwj1994/dataforge/tree/main/dataforge_base
repository: https://github.com/lwj1994/dataforge/tree/main/dataforge_base

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.0
  analyzer: ^8.1.1
