name: data_class_annotation
description: Annotations for data_class_gen package to generate data classes with JSON serialization support.
version: 0.1.0-dev.0
homepage: https://github.com/your_username/dart_data_class_gen
repository: https://github.com/your_username/dart_data_class_gen
issue_tracker: https://github.com/your_username/dart_data_class_gen/issues
documentation: https://github.com/your_username/dart_data_class_gen#readme

environment:
  sdk: ^3.0.0